version: '3.8'

services:
  rhythmix-home-web:
    container_name: rhythmix-home-web
    build:
      context: ./frontend/rhythmix-home-web
      dockerfile: DockerFile
    ports:
      - "3002:80"              
    environment:
      - NODE_ENV=production

  rhythmix-library-web:
    container_name: rhythmix-library-web
    build:
      context: ./frontend/rhythmix-library-web
      dockerfile: DockerFile
    ports:
      - "3001:80"              
    environment:
      - NODE_ENV=production

  rhythmix-player-web:
    container_name: rhythmix-player-web
    build:
      context: ./frontend/rhythmix-player-web
      dockerfile: DockerFile
    ports:
      - "3000:80"              
    environment:
      - NODE_ENV=production

  rhythmix-web:
    container_name: rhythmix-web
    depends_on:
      - rhythmix-home-web
      - rhythmix-library-web
    build:
      context: ./frontend/rhythmix-web
      dockerfile: DockerFile
    ports:
      - "5173:80"              
    environment:
      - NODE_ENV=production
