version: '3.8'

services:
  rhythmix-home-web:
    container_name: rhythmix-home-web
    build:
      context: ./frontend/rhythmix-home-web
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production

  rhythmix-library-web:
    container_name: rhythmix-library-web
    build:
      context: ./frontend/rhythmix-library-web
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production

  rhythmix-player-web:
    container_name: rhythmix-player-web
    build:
      context: ./frontend/rhythmix-player-web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  rhythmix-web:
    container_name: rhythmix-web
    depends_on:
      rhythmix-home-web:
        condition: service_started
      rhythmix-library-web:
        condition: service_started
      rhythmix-player-web:
        condition: service_started
      rhythmix-config-server:
        condition: service_healthy
    build:
      context: ./frontend/rhythmix-web
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production

  rhythmix-postgres:
    container_name: rhythmix-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rhythmix
      - POSTGRES_USER=rhythmix
      - POSTGRES_PASSWORD=rhythmix
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "rhythmix" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  rhythmix-config-server:
    container_name: rhythmix-config-server
    build:
      context: ./backend/rhythmix-config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  rhythmix-auth-service:
    container_name: rhythmix-auth-service
    depends_on:
      rhythmix-config-server:
        condition: service_healthy
      rhythmix-gateway:
        condition: service_started
    restart: unless-stopped
    build:
      context: ./backend/rhythmix-auth-service
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - CONFIG_SERVER_URL=http://rhythmix-config-server:8888
      - SPRING_PROFILES_ACTIVE=dev
      - USER_SERVICE_BASE_URL=http://rhythmix-user-services:8080

  rhythmix-song-service:
    container_name: rhythmix-song-service
    depends_on:
      rhythmix-postgres:
        condition: service_healthy
      rhythmix-config-server:
        condition: service_healthy
      rhythmix-gateway:
        condition: service_started
    restart: unless-stopped
    build:
      context: ./backend/rhythmix-song-service
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    environment:
      - POSTGRES_JDBC_URL=jdbc:postgresql://rhythmix-postgres:5432/rhythmix
      - CONFIG_SERVER_URL=http://rhythmix-config-server:8888
      - SPRING_PROFILES_ACTIVE=dev

  rhythmix-user-services:
    container_name: rhythmix-user-services
    depends_on:
      rhythmix-postgres:
        condition: service_healthy
      rhythmix-config-server:
        condition: service_healthy
      rhythmix-gateway:
        condition: service_started
    restart: unless-stopped
    build:
      context: ./backend/rhythmix-user-services
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_JDBC_URL=jdbc:postgresql://rhythmix-postgres:5432/rhythmix
      - SPRING__CLOUD__CONFIG__URI=http://rhythmix-config-server:8888
      - SPRING__PROFILES__ACTIVE=Production
      - ASPNETCORE_ENVIRONMENT=Production

  rhythmix-gateway:
    container_name: rhythmix-gateway
    build:
      context: ./backend/rhythmix-gateway
      dockerfile: Dockerfile
    depends_on:
      rhythmix-config-server:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      - rhythmix_auth_service_url=http://rhythmix-auth-service:8100
      - rhythmix_user_service_url=http://rhythmix-user-services:8080
      - rhythmix_song_service_url=http://rhythmix-song-service:8200
      - AUTH_SERVICE_BASE_URL=http://rhythmix-auth-service:8100/auth
      - CONFIG_SERVER_URL=http://rhythmix-config-server:8888
      - SPRING_PROFILES_ACTIVE=dev
      - FRONTEND_URL=http://localhost:5173

