import type { LyricsLine, SongMetadata } from "./musicPlayer.ts";

const mockLyrics: LyricsLine[] = [
  { time: 10, text: "Hum tere bin ab reh nahi sakte" },
  { time: 15, text: "Tere bina kya wajood mera" },
  { time: 25, text: "Hum tere bin ab reh nahi sakte" },
  { time: 30, text: "Tere bina kya wajood mera" },
  { time: 35, text: "Tujhse juda gar ho jaayenge" },
  { time: 40, text: "Toh khud se hi ho jaayenge judaa" },
  { time: 48, text: "Kyunki tum hi ho" },
  { time: 50, text: "Ab tum hi ho" },
  { time: 53, text: "Zindagi ab tum hi ho" },
  { time: 58, text: "Chain bhi, mera dard bhi" },
  { time: 63, text: "Meri aashiqui ab tum hi ho" },
  { time: 89, text: "Tera mera rishta hai kaisa" },
  { time: 94, text: "Ik pal door gawara nahi" },
  { time: 99, text: "Tere liye har roz hai jeete" },
  { time: 104, text: "Tujh ko diya mera waqt sabhi" },
  { time: 109, text: "Koi lamha mera na ho tere bina" },
  { time: 114, text: "Har saans pe naam tera" },
  { time: 122, text: "Kyunki tum hi ho" },
  { time: 124, text: "Ab tum hi ho" },
  { time: 127, text: "Zindagi ab tum hi ho" },
  { time: 132, text: "Chain bhi, mera dard bhi" },
  { time: 137, text: "Meri aashiqui ab tum hi ho" },
  { time: 159, text: "Tumhi ho... Tumhi ho..." },
  { time: 173, text: "Tere liye hi jiya main" },
  { time: 178, text: "Khud ko jo yun de diya hai" },
  { time: 182, text: "Teri wafa ne mujhko sambhala" },
  { time: 188, text: "Saare ghamon ko dil se nikala" },
  { time: 193, text: "Tere saath mera hai naseeb juda" },
  { time: 198, text: "Tujhe paake adhoora naa raha hmm..." },
  { time: 206, text: "Kyunki tum hi ho" },
  { time: 209, text: "Ab tum hi ho" },
  { time: 211, text: "Zindagi ab tum hi ho..." },
  { time: 216, text: "Chain bhi, mera dard bhi" },
  { time: 221, text: "Meri aashiqui ab tum hi ho" },
  { time: 227, text: "Kyunki tum hi ho" },
  { time: 229, text: "Ab tum hi ho" },
  { time: 232, text: "Zindagi ab tum hi ho..." },
  { time: 237, text: "Chain bhi, mera dard bhi" },
  { time: 241, text: "Meri aashiqui ab tum hi ho" }
];

const mockLyrics2: LyricsLine[] = [
  { time: 0, text: "(Church-Church-Church)" },
  { time: 2, text: "(Churchil dái in the beat)" },
  { time: 5, text: "Yeah" },
  { time: 7, text: "Paisaa (paisaa) tãsanga, mm-hm" },
  { time: 10, text: "Paisaa mãsanga, yeah" },
  { time: 13, text: "Paisaa (paisaa) tãsanga, mm-hm" },
  { time: 16, text: "Paisaa mãsanga, yeah" },
  { time: 19, text: "Paisaa (paisaa) tãsanga, mm-hm" },
  { time: 22, text: "Paisaa mãsanga, yeah" },
  { time: 25, text: "Paisaa (paisaa) tãsanga, mm-hm" },
  { time: 28, text: "Paisaa mãsanga, yeah" },
  { time: 31, text: "Paisaa chha dough, overload cash flow" },
  { time: 34, text: "Bro, bhaisakẽ bor, gani nasakine bho (ho)" },
  { time: 37, text: "Paisaa ko bot, paisaa jaḍeko coat mero" },
  { time: 40, text: "Hãshera bitáide ājabholiko nasoch, keṭo" },
  { time: 43, text: "Paisaa tãsanga, mm-hm" },
  { time: 46, text: "Paisaa (paisaa) mãsanga, yeah" },
  { time: 49, text: "Paisaa tãsanga, mm-hm" },
  { time: 52, text: "Paisaa (paisaa) mãsanga, yeah" },
  { time: 55, text: "Dhani ṭhūlo, choḍ kuro, money kuro bol ṭhūlo" },
  { time: 58, text: "Bhani ḍubo, pol khulo, ani bujho, soch kuro" },
  { time: 61, text: "Ambani ko Antilia mā kholidinchu penṭikhānā" },
  { time: 64, text: "Paisaa yeti dherai, solṭi, kamāyerai senti bhā ma" },
  { time: 67, text: "Āyo paisaa, gayo paisaa, dherai āyo, thorai laijā" },
  { time: 70, text: "Khāyo paisaa, hāgo aisā, beche āu̐cha Mona Lisa" },
  { time: 73, text: "Steve Jobs, better not fu*k with me dherai, 'cause" },
  { time: 76, text: "Kindinchu tero all company feri ma" },
  { time: 79, text: "Paisaa tãsanga, mm-hm" },
  { time: 82, text: "Paisaa (paisaa) mãsanga, yeah" },
  { time: 85, text: "Paisaa tãsanga, mm-hm" },
  { time: 88, text: "Paisaa (paisaa) mãsanga, yeah" },
  { time: 91, text: "Shah Rukh lāi loan bhāk, Salman ko donor ma" },
  { time: 94, text: "Paisaa ko golmāl, bāṇijyako owner ma" },
  { time: 97, text: "Sā̃ccikai bhaneko kuro sundā feri ṭhaṭṭā lācha" },
  { time: 100, text: "Candramā mā jaggā mero, dhanī purjā pakkā bhācha" },
  { time: 103, text: "Pā̃c dekhi daś, bīs, saya, pacās, mastī" },
  { time: 106, text: "Sakyo? La, parkhi, print huncha parsi" },
  { time: 109, text: "Facebook ra Insta, yo Twitter ko cintā" },
  { time: 112, text: "Bhan, kati lāgcha paisaa yo tīntai lāi kindā, hā?" },
  { time: 115, text: "Paisaa tãsanga, mm-hm" },
  { time: 118, text: "Paisaa (paisaa) mãsanga, yeah" },
  { time: 121, text: "Paisaa tãsanga, mm-hm" },
  { time: 124, text: "Paisaa (paisaa) mãsanga, yeah" },
  { time: 127, text: "Bezos nai riṇmā jaba chirchu ma scene mā" },
  { time: 130, text: "Bhāi Chaudhary lāi siṅgai pacāidinchu ekchinmā" },
  { time: 133, text: "Musk Elon le Tesla lāi katimā po beclā?" },
  { time: 136, text: "Bhan, testā mulā kinne paisaa bokī hiḍchu jebmā" },
  { time: 139, text: "Louis Vuitton, Zara, yo Gucci ra Prada ko" },
  { time: 142, text: "Uṭhāuchu ma bhāḍā sadhaī America jādā" },
  { time: 145, text: "Yo Andrew ko Tate ani Billy bhāiko gate pani" },
  { time: 148, text: "Joḍī mero net jati pugdaina bheṭna ni" },
  { time: 151, text: "Jeff pani bec, kati tespachi pani ajhai" },
  { time: 154, text: "Days kati lāgcha tãlāi yā̃ pugna? Decades jati" },
  { time: 157, text: "Hā, hā, tetī paisaa chha, bro" },
  { time: 160, text: "Paisaa tãsanga, mm-hm" },
  { time: 163, text: "Paisaa mãsanga, yeah" },
  { time: 166, text: "Paisaa tãsanga, mm-hm" },
  { time: 169, text: "Paisaa mãsanga, yeah" },
  { time: 172, text: "Paisaa tãsanga, mm-hm" },
  { time: 175, text: "Paisaa mãsanga, yeah" },
  { time: 178, text: "Paisaa tãsanga, mm-hm" },
  { time: 181, text: "Paisaa mãsanga, yeah" }
];

const mockLyrics3: LyricsLine[] = [
  { time: 13, text: "Diamond de naal tolda" },
  { time: 16, text: "Jinna tera bhar goriye" },
  { time: 18, text: "Gabru taan vairi nu vi mitha bolda" },
  { time: 20, text: "Ni tu taan phir jatt da pyar goriye" },
  { time: 23, text: "Dekh bollywood vich jinne Khan ne" },
  { time: 26, text: "Ohna vich behnda sardar goriye" },
  { time: 29, text: "Gabru taan vairi nu vi mitha bolda" },
  { time: 31, text: "Ni tu taan phir jatt da pyar goriye" },
  { time: 34, text: "Tera rakha main rab rakha yaar da" },
  { time: 37, text: "Naam jihda laawan uthe saar goriye" },
  { time: 40, text: "Gabru taan vairi nu vi mitha bolda" },
  { time: 42, text: "Ni tu taan phir jatt da pyar goriye" },
  { time: 46, text: "Jolly gut bainde baala aali pag dekhdi" },
  { time: 48, text: "Vekh gaur naal gabru chon agg dikhdi" },
  { time: 51, text: "Mitha jatt kaude ghut na peevan jattiye" },
  { time: 54, text: "Matt uchchi mera man jama niwan jattiye" },
  { time: 57, text: "Pichhe kudiyan da kafala" },
  { time: 59, text: "Window taan ni deva hath maar goriye" },
  { time: 61, text: "Gabru taan vairi nu vi mitha bolda" },
  { time: 64, text: "Ni tu taan phir jatt da pyar goriye" },
  { time: 67, text: "Gall vich paya 40 lakh bolda" },
  { time: 70, text: "Dollar ch 80 ik hazar goriye" },
  { time: 72, text: "Gabru taan vairi nu vi mitha bolda" },
  { time: 75, text: "Ni tu taan phir jatt da pyar goriye" },
  { time: 100, text: "Ho chal dass hi dinna je gall tauri ni" },
  { time: 103, text: "Badi lambi success di story ni" },
  { time: 105, text: "Kude ban ke taan dekh tera Kaur Singh di ni" },
  { time: 108, text: "Dekh moam de statue ch vi taur Singh di" },
  { time: 111, text: "Agge da pata ni jatt nu" },
  { time: 113, text: "Changa chali janda so far goriye" },
  { time: 116, text: "Gabru taan vairi nu vi mitha bolda" },
  { time: 119, text: "Ni tu taan phir jatt da pyar goriye" },
  { time: 122, text: "Ohne long race wale ghode sunn lai" },
  { time: 124, text: "Jihna utte assi aan sawar goriye" },
  { time: 127, text: "Gabru taan vairi nu vi mitha bolda" },
  { time: 129, text: "Ni tu taan phir jatt da pyar goriye" },
  { time: 142, text: "Ae yo G-Funk!" },
  { time: 155, text: "Ho enha ho gaya tazurba ni sikheya peya" },
  { time: 157, text: "Hale wish aa peya de utte tikkeya peya" },
  { time: 160, text: "Ghumi game aaya fame jatt same ni" },
  { time: 163, text: "Kar search Dosanjh’aa aala name ni" },
  { time: 166, text: "Tera Aujla ni Aujla" },
  { time: 168, text: "Baahleyan di range vichon bahar goriye" },
  { time: 171, text: "Gabru taan vairi nu vi mitha bolda" },
  { time: 173, text: "Ni tu taan phir jatt da pyar goriye" },
  { time: 176, text: "Chan chan aakh ke bulaya kar tu" },
  { time: 179, text: "Log bhawein kehnde ne star goriye" },
  { time: 182, text: "Gabru taan vairi nu vi mitha bolda" },
  { time: 184, text: "Ni tu taan phir jatt da pyar goriye" }
];

const trackList: SongMetadata[] = [
  {
    url: "https://pagalall.com/wp-content/uploads/all/Tum%20Hi%20Ho%20Aashiqui%202%20(pagalall.com).mp3",
    title: "Tum Hi Ho",
    artist: "Arijit Singh",
    album: "Aashiqui",
    coverArt: "https://i.scdn.co/image/ab67616d0000b2736404721c1943d5069f0805f3",
    lyrics: mockLyrics,
    id: "1",
  },
  {
    url: "https://pagalall.com/wp-content/uploads/all/Paisa%20-%E2%80%AC%20Taaza%20Khabar%20Season%202%20(pagalall.com).mp3",
    title: "Paisaa",
    artist: "Kushal Grumpy",
    album: "Paisaa",
    coverArt: "https://m.media-amazon.com/images/M/MV5BN2Y4M2ZiNjQtZDYxMS00MGY4LTlhMjYtODdlMTNmYWIzOWE3XkEyXkFqcGc@._V1_.jpg",
    id: "2",
    lyrics: mockLyrics2
  },
  {
    url: "https://pagalfree.com/download/128-GOAT%20-%20GOAT%20128%20Kbps.mp3",
    title: "GOAT",
    artist: "Diljit Dosanjh",
    album: "GOAT",
    coverArt: "https://i1.sndcdn.com/artworks-TxeyXAXkvyQLKwE6-jN9Q0w-t500x500.jpg",
    id: "3",
    lyrics: mockLyrics3
  }
];

export default trackList;