-- --------------------------------------------------
-- 1) Seed the `song` table with 7 tracks
-- --------------------------------------------------
INSERT INTO song (id, url, album, genre, language, artist, title, cover_art, created_at) VALUES
  (1,
   'https://pagalall.com/wp-content/uploads/all/Tum%20Hi%20Ho%20Aashiqui%202%20(pagalall.com).mp3',
   'Aashiqui',
   'Romantic Bollywood',
   'Hindi',
   'Arijit Singh',
   'Tum Hi Ho',
   'https://i.scdn.co/image/ab67616d0000b2736404721c1943d5069f0805f3',
   NOW()
  ),
  (2,
   'https://pagalall.com/wp-content/uploads/all/Paisa%20-%E2%80%AC%20Taaza%20Khabar%20Season%202%20(pagalall.com).mp3',
   'Paisaa',
   'Hip-Hop/Rap',
   'Hindi',
   'Kushal Grumpy',
   'Paisaa',
   'https://m.media-amazon.com/images/M/MV5BN2Y4M2ZiNjQtZDYxMS00MGY4LTlhMjYtODdlMTNmYWIzOWE3XkEyXkFqcGc@._V1_.jpg',
   NOW()
  ),
  (3,
   'https://pagalfree.com/download/128-GOAT%20-%20GOAT%20128%20Kbps.mp3',
   'GOAT',
   'Punjabi Pop',
   'Punjabi',
   'Diljit Dosanjh',
   'GOAT',
   'https://i1.sndcdn.com/artworks-TxeyXAXkvyQLKwE6-jN9Q0w-t500x500.jpg',
   NOW()
  ),
  (4,
   'https://pagalfree.com/download/128-Nasha%20-%20Raid%202%20128%20Kbps.mp3',
   'Raid 2',
   'Soft Rock',
   'Hindi',
   'Amar Jalal',
   'Nasha',
   'https://pagalfree.com/images/128Nasha%20-%20Raid%202%20128%20Kbps.jpg',
   NOW()
  ),
  (5,
   'https://pagalfree.com/download/128-Laal%20Pari%20-%20Housefull%205%20128%20Kbps.mp3',
   'Housefull 5',
   'Dance/Bollywood',
   'Hindi',
   'Mika Singh',
   'Laal Pari',
   'https://pagalfree.com/images/128Laal%20Pari%20-%20Housefull%205%20128%20Kbps.jpg',
   NOW()
  ),
  (6,
   'https://pagalfree.com/download/128-Apna%20Bana%20Le%20-%20Bhediya%20128%20Kbps.mp3',
   'Bhediya',
   'Bollywood Soundtrack',
   'Hindi',
   'Arijit Singh',
   'Apna Bana Le',
   'https://pagalfree.com/images/128Apna%20Bana%20Le%20-%20Bhediya%20128%20Kbps.jpg',
   NOW()
  ),
  (7,
   'https://pagalfree.com/download/128-Kalank%20(Title%20Track)%20-%20Kalank%20128%20Kbps.mp3',
   'Kalank',
   'Film Score',
   'Hindi',
   'Arijit Singh',
   'Kalank (Title Track)',
'https://pagalfree.com/images/128Kalank%20(Title%20Track)%20-%20Kalank%20128%20Kbps.jpg',
NOW()
),
(8,
'https://pagalall.com/wp-content/uploads/all/Jaadu%20Jewel%20Thief%20(pagalall.com).mp3',
'Jewel Thief',
'Bollywood',
'Hindi',
'Raghav Chaitanya',
'Jaadu',
'https://pagalall.com/wp-content/uploads/Jaadu-Jewel-Thief-pagalall.com_.jpg',
NOW()
),
(9,
'https://pagalall.com/wp-content/uploads/all/Hookah%20Bar%20Khiladi%20786%20(pagalall.com).mp3',
'Khiladi 786',
'Bollywood,Party',
'Hindi',
'Himesh Reshammiya',
'Hookah Bar',
'https://pagalall.com/wp-content/uploads/Hookah-Bar-Khiladi-786-pagalall.com_.jpg',
NOW()
),
(10,
'https://pagalall.com/wp-content/uploads/all/Saans%20Jab%20Tak%20Hai%20Jaan%20(pagalall.com).mp3',
'Jab Tak Hai Jaan',
'Bollywood,Love',
'Hindi',
'Shreya Ghoshal, Mohit Chauhan',
'Saans',
'https://pagalall.com/wp-content/uploads/Saans-Jab-Tak-Hai-Jaan-pagalall.com_.jpg',
NOW()
),
(11,
'https://pagalall.com/wp-content/uploads/all/Challa%20Jab%20Tak%20Hai%20Jaan%20(pagalall.com).mp3',
'Jab Tak Hai Jaan',
'Bollywood',
'Hindi',
'Rabbi Shergill',
'Challa',
'https://pagalall.com/wp-content/uploads/Challa-Jab-Tak-Hai-Jaan-pagalall.com_.jpg',
NOW()
),
(12,
'https://pagalall.com/wp-content/uploads/all/Dagabaaz%20Re%20Dabangg%202%20(pagalall.com).mp3',
'Dabangg 2',
'Bollywood',
'Hindi',
'Rahat Fateh Ali Khan, Shreya Ghoshal',
'Dagabaaz Re',
'https://pagalall.com/wp-content/uploads/Dagabaaz-Re-Dabangg-2-pagalall.com_.jpg',
NOW()
),
(13,
'https://pagalall.com/wp-content/uploads/all/Mein%20Sharabi%20Cocktail%20(pagalall.com).mp3',
'Cocktail',
'Bollywood,Party',
'Hindi',
'Imtiaz Ali, Sajid Ali',
'Mein Sharabi',
'https://pagalall.com/wp-content/uploads/Mein-Sharabi-Cocktail-pagalall.com_.jpg',
NOW()
),
(14,
'https://pagalall.com/wp-content/uploads/all/Jugni%20Cocktail%20(pagalall.com).mp3',
'Cocktail',
'Bollywood',
'Hindi,Punjabi',
'Arif Lohar, Harshdeep Kaur',
'Jugni',
'https://pagalall.com/wp-content/uploads/Jugni-Cocktail-pagalall.com_.jpg',
NOW()
),
(15,
'https://pagalall.com/wp-content/uploads/all/Sunny%20Sunny%20Yaariyan%20(pagalall.com).mp3',
'Yaariyan',
'Bollywood,Party',
'Hindi',
'Yo Yo Honey Singh, Neha Kakkar',
'Sunny Sunny',
'https://pagalall.com/wp-content/uploads/Sunny-Sunny-Yaariyan-pagalall.com_.jpg',
NOW()
),
(16,
'https://pagalall.com/wp-content/uploads/all/Baarish%20Yaariyan%20Yaariyan%20(pagalall.com).mp3',
'Yaariyan',
'Bollywood,Love',
'Hindi',
'Mohammed Irfan, Gajendra Verma',
'Baarish',
'https://pagalall.com/wp-content/uploads/Sunny-Sunny-Yaariyan-pagalall.com_.jpg',
NOW()
),
(17,
'https://pagalall.com/wp-content/uploads/all/Rang%20Jo%20Lagyo%20Ramaiya%20Vastavaiya%20(pagalall.com).mp3',
'Ramaiya Vastavaiya',
'Bollywood,Love',
'Hindi',
'Atif Aslam, Shreya Ghoshal',
'Rang Jo Lagyo',
'https://pagalall.com/wp-content/uploads/Rang-Jo-Lagyo-Ramaiya-Vastavaiya-pagalall.com_.jpg',
NOW()
),
(18,
'https://pagalall.com/wp-content/uploads/all/Jeene%20Laga%20Hoon%20Ramaiya%20Vastavaiya%20(pagalall.com).mp3',
'Ramaiya Vastavaiya',
'Bollywood,Love',
'Hindi',
'Atif Aslam, Shreya Ghoshal',
'Jeene Laga Hoon',
'https://pagalall.com/wp-content/uploads/Rang-Jo-Lagyo-Ramaiya-Vastavaiya-pagalall.com_.jpg',
NOW()
),
(19,
'https://pagalall.com/wp-content/uploads/all/Teri%20Jhuki%20Nazar%20Murder%203%20(pagalall.com).mp3',
'Murder 3',
'Bollywood,Love',
'Hindi',
'Shafqat Amanat Ali',
'Teri Jhuki Nazar',
'https://pagalall.com/wp-content/uploads/Teri-Jhuki-Nazar-Murder-3-pagalall.com_.jpg',
NOW()
),
(20,
'https://pagalall.com/wp-content/uploads/Tumhein%20Dillagi%20Bhool%20Jani%20Paray%20Gi%20-%20Nusrat%20Fateh%20Ali%20Khan%20(pagalall.com).mp3',
'Tumhein Dillagi Bhool Jani Paray Gi',
'Qawwali',
'Hindi',
'Ustad Nusrat Fateh Ali Khan',
'Tumhein Dillagi Bhool Jani Paray Gi',
'https://pagalall.com/wp-content/uploads/Tumhein-Dillagi-Bhool-Jani-Paray-Gi-Nusrat-Fateh-Ali-Khan-pagalall.com_.jpg',
NOW()
),
(21,
'https://pagalall.com/wp-content/uploads/all/Mere%20Rashke%20Qamar%20-%20Baadshaho%20(pagalall.com).mp3',
'Baadshaho',
'Qawwali',
'Hindi',
'Nusrat Fateh Ali Khan, Rahat Fateh Ali Khan',
'Mere Rashke Qamar',
'https://pagalall.com/wp-content/uploads/Mere-Rashke-Qamar-Baadshaho-pagalall.com_.jpg',
NOW()
),
(22,
'https://pagalall.com/wp-content/uploads/all/Jee%20Le%20Zaraa%20Talaash%20(pagalall.com).mp3',
'Talaash',
'Bollywood,Love',
'Hindi',
'Vishal Dadlani',
'Jee Le Zaraa',
'https://pagalall.com/wp-content/uploads/Jee-Le-Zaraa-Talaash-pagalall.com_.jpg',
NOW()
),
(23,
'https://pagalall.com/wp-content/uploads/all/Po%20Po%20Son%20Of%20Sardaar%20(pagalall.com).mp3',
'Son of Sardaar',
'Bollywood',
'Punjabi',
'Vikas Bhalla, Aman Trikha & Himesh Reshammiya',
'Po Po',
'https://pagalall.com/wp-content/uploads/Kabhi-Kabhi-Mere-Dil-Mein-Yeh-Sawaal-Aata-Hai-House-Track-Trance-Son-Of-Sardaar-pagalall.com_.jpg',
NOW()
),
(24,
'https://pagalall.com/wp-content/uploads/all/Lonely%20Khiladi%20786%20(pagalall.com).mp3',
'Khiladi 786',
'Bollywood',
'Hindi',
'Himesh Reshammiya, Yo Yo Honey Singh & Hamsika Iyer',
'Lonely',
'https://pagalall.com/wp-content/uploads/Lonely-Khiladi-786-pagalall.com_.jpg',
NOW()
),
(25,
'https://pagalall.com/wp-content/uploads/all/Tantrums%20Paradox%20(pagalall.com).mp3',
'Tantrums',
'Rap',
'Hindi',
'Paradox',
'Tantrums',
'https://pagalall.com/wp-content/uploads/Tantrums-Paradox-pagalall.com_.jpg',
NOW()
),
(26,
'https://pagalall.com/wp-content/uploads/all/Bali%20Battle%20Little%20Bhatia%20(pagalall.com).mp3',
'MTV Hustle',
'Rap',
'Hindi,Punjabi',
'Little Bhatia',
'Bali Battle',
'https://pagalall.com/wp-content/uploads/Bali-Battle-Little-Bhatia-pagalall.com_.jpg',
NOW()
),
(27,
'https://pagalall.com/wp-content/uploads/all/Angad%20Little%20Bhatia%20(pagalall.com).mp3',
'MTV Hustle',
'Rap',
'Hindi,Punjabi',
'Little Bhatia',
'Angad',
'https://pagalall.com/wp-content/uploads/Bali-Battle-Little-Bhatia-pagalall.com_.jpg',
NOW()
),
(28,
'https://pagalall.com/wp-content/uploads/all/Chowk%20Pe%2099side%20(pagalall.com).mp3',
'MTV Hustle',
'Rap',
'Hindi,Marathi',
'99side',
'Chowk Pe',
'https://pagalall.com/wp-content/uploads/Bali-Battle-Little-Bhatia-pagalall.com_.jpg',
NOW()
),
(29,
'https://pagalall.com/wp-content/uploads/all/Vishay%20Khatam%20Naam%20Sujal%20(pagalall.com).mp3',
'MTV Hustle',
'Rap',
'Hindi',
'Naam Sujal',
'Vishay Khatam',
'https://pagalall.com/wp-content/uploads/Bali-Battle-Little-Bhatia-pagalall.com_.jpg',
NOW()
),
(30,
'https://pagalall.com/wp-content/uploads/all/Laundey%20Crazy%20Pho%20(pagalall.com).mp3',
'MTV Hustle',
'Rap',
'Hindi',
'Pho',
'Laundey Crazy',
'https://pagalall.com/wp-content/uploads/Bali-Battle-Little-Bhatia-pagalall.com_.jpg',
NOW()
),
(31,
'https://pagalall.com/wp-content/uploads/Raat%20Ki%20Rani%20-%20Seedhe%20Maut%20(pagalall.com).mp3',
'SHAKTI',
'Rap',
'Hindi',
'Seedhe Maut',
'Raat Ki Rani',
'https://pagalall.com/wp-content/uploads/Raat-Ki-Rani-Seedhe-Maut-pagalall.com_.jpg',
NOW()
),
(32,
'https://pagalall.com/wp-content/uploads/all/Maniac%20Yo%20Yo%20Honey%20Singh%20(pagalall.com).mp3',
'Glory',
'Rap',
'Hindi,Bhojpuri',
'Yo Yo Honey Singh',
'Maniac',
'https://pagalall.com/wp-content/uploads/Maniac-Yo-Yo-Honey-Singh-pagalall.com_.jpg',
NOW()
),
(33,
'https://pagalall.com/wp-content/uploads/Hass%20Hass%20-%20Diljit%20Dosanjh%20x%20Sia%20(pagalall.com).mp3',
'Hass Hass',
'PunjabiPop',
'Punjabi, English',
'Diljit Dosanjh, Sia, Greg Kurstin',
'Hass Hass Diljit Dosanjh x Sia',
'https://pagalall.com/wp-content/uploads/Hass-Hass-Diljit-Dosanjh-x-Sia-pagalall.com_.jpg',
NOW()
),
(34,
'https://pagalall.com/wp-content/uploads/all/Chalao%20Na%20Naino%20Se%20Bol%20Bachchan%20(pagalall.com).mp3',
'Bol Bachchan',
'Bollywood,Love',
'Hindi',
'Himesh Reshammiya, Shreya Ghoshal',
'Chalao Na Naino Se',
'https://pagalall.com/wp-content/uploads/Chalao-Na-Naino-Se-Bol-Bachchan-pagalall.com_.jpg',
NOW()
),
(35,
'hhttps://pagalall.com/wp-content/uploads/all/Mukhtasar%20Teri%20Meri%20Kahaani%20(pagalall.com).mp3',
'Teri Meri Kahaani',
'Bollywood,Love,Party',
'Hindi',
'Wajid',
'Mukhtasar',
'https://pagalall.com/wp-content/uploads/Mukhtasar-Teri-Meri-Kahaani-pagalall.com_.jpg',
NOW()
),
(36,
'https://pagalall.com/wp-content/uploads/all/Shirt%20Da%20Button%20Kyaa%20Super%20Kool%20Hain%20Hum%20(pagalall.com).mp3',
'Kyaa Super Kool Hain Hum',
'Bollywood',
'Hindi,Punjabi',
'Sonu Nigam,Meet Bros',
'Shirt Da Button',
'https://pagalall.com/wp-content/uploads/Shirt-Da-Button-Kyaa-Super-Kool-Hain-Hum-pagalall.com_.jpg',
NOW()
),
(37,
'https://pagalall.com/wp-content/uploads/all/Dil%20Garden%20Garden%20Ho%20Gaya%20Kyaa%20Super%20Kool%20Hain%20Hum%20(pagalall.com).mp3',
'Kyaa Super Kool Hain Hum',
'Bollywood',
'Hindi',
'Vishal Dadlani',
'Dil Garden Garden Ho Gaya',
'https://pagalall.com/wp-content/uploads/Shirt-Da-Button-Kyaa-Super-Kool-Hain-Hum-pagalall.com_.jpg',
NOW()
),
(38,
'https://pagalall.com/wp-content/uploads/all/Yeh%20Jism%20Jism%202%20(pagalall.com).mp3',
'Jism 2',
'Love',
'Hindi',
'Ali Azmat',
'Yeh Jism',
'https://pagalall.com/wp-content/uploads/Yeh-Jism-Jism-2-pagalall.com_.jpg',
NOW()
),
(39,
'https://pagalall.com/wp-content/uploads/all/Abhi%20Abhi%20(Male)%20Jism%202%20(pagalall.com).mp3',
'Jism 2',
'Love',
'Hindi',
'K.K',
'Abhi Abhi (Male)',
'https://pagalall.com/wp-content/uploads/Yeh-Jism-Jism-2-pagalall.com_.jpg',
NOW()
),
(40,
'https://pagalall.com/wp-content/uploads/all/Womaniya%20Gangs%20Of%20Wasseypur%20(pagalall.com).mp3',
'Gangs Of Wasseypur',
'Bollywood',
'Hindi,Bihari',
'Khushboo Raj, Rekha Jha',
'O Womaniya',
'https://pagalall.com/wp-content/uploads/Womaniya-Gangs-Of-Wasseypur-pagalall.com_.jpg',
NOW()
),
(41,
'https://pagalall.com/wp-content/uploads/all/Ik%20Bagal%20Gangs%20Of%20Wasseypur%20(pagalall.com).mp3',
'Gangs Of Wasseypur',
'Bollywood',
'Hindi',
'Piyush Mishra',
'Ik Bagal',
'https://pagalall.com/wp-content/uploads/Womaniya-Gangs-Of-Wasseypur-pagalall.com_.jpg',
NOW()
),
(42,
'https://pagalall.com/wp-content/uploads/all/Hunter%20Gangs%20Of%20Wasseypur%20(pagalall.com).mp3',
'Gangs Of Wasseypur',
'Bollywood',
'Hindi',
'Vedesh Sookoo, Rajneesh, Shyamo, Munna',
'I am Hunter',
'https://pagalall.com/wp-content/uploads/Womaniya-Gangs-Of-Wasseypur-pagalall.com_.jpg',
NOW()
),
(43,
'https://pagalall.com/wp-content/uploads/all/Vele%20Student%20of%20the%20Year%20(pagalall.com).mp3',
'Student of the Year',
'Bollywood',
'Hindi,Punjabi',
'Vishal Dadlani, Shekhar Ravjiani',
'Vele',
'https://pagalall.com/wp-content/uploads/Vele-Student-of-the-Year-pagalall.com_.jpg',
NOW()
),
(44,
'https://pagalall.com/wp-content/uploads/all/Ishq%20Wala%20Love%20Student%20of%20the%20Year%20(pagalall.com).mp3',
'Student of the Year',
'Bollywood',
'Hindi',
'Salim Merchant, Neeti Mohan, Shekhar Ravjiani',
'Ishq Wala Love',
'https://pagalall.com/wp-content/uploads/Vele-Student-of-the-Year-pagalall.com_.jpg',
NOW()
),
(45,
'https://pagalall.com/wp-content/uploads/all/Sun%20Soniye%20Ajab%20Gazabb%20Love%20(pagalall.com).mp3',
'Ajab Gazabb Love',
'Bollywood',
'Hindi',
'Mohammed Irfan, Antara Mitra',
'Sun Soniye',
'https://pagalall.com/wp-content/uploads/Sun-Soniye-Ajab-Gazabb-Love-pagalall.com_.jpg',
NOW()
);
-- --------------------------------------------------
-- 2) Seed the `song_lyrics` table for each track
--    We assign artificial PKs starting from 1000.
-- --------------------------------------------------

-- Lyrics for song_id = 1 (Tum Hi Ho)
INSERT INTO song_lyrics (id, time, text, song_id) VALUES
  (1000, 10, 'Hum tere bin ab reh nahi sakte', 1),
  (1001, 15, 'Tere bina kya wajood mera', 1),
  (1002, 25, 'Hum tere bin ab reh nahi sakte', 1),
  (1003, 30, 'Tere bina kya wajood mera', 1),
  (1004, 35, 'Tujhse juda gar ho jaayenge', 1),
  (1005, 40, 'Toh khud se hi ho jaayenge judaa', 1),
  (1006, 48, 'Kyunki tum hi ho', 1),
  (1007, 50, 'Ab tum hi ho', 1),
  (1008, 53, 'Zindagi ab tum hi ho', 1),
  (1009, 58, 'Chain bhi, mera dard bhi', 1),
  (1010, 63, 'Meri aashiqui ab tum hi ho', 1),
  (1011, 89, 'Tera mera rishta hai kaisa', 1),
  (1012, 94, 'Ik pal door gawara nahi', 1),
  (1013, 99, 'Tere liye har roz hai jeete', 1),
  (1014, 104, 'Tujh ko diya mera waqt sabhi', 1),
  (1015, 109, 'Koi lamha mera na ho tere bina', 1),
  (1016, 114, 'Har saans pe naam tera', 1),
  (1017, 122, 'Kyunki tum hi ho', 1),
  (1018, 124, 'Ab tum hi ho', 1),
  (1019, 127, 'Zindagi ab tum hi ho', 1),
  (1020, 132, 'Chain bhi, mera dard bhi', 1),
  (1021, 137, 'Meri aashiqui ab tum hi ho', 1),
  (1022, 159, 'Tumhi ho... Tumhi ho...', 1),
  (1023, 173, 'Tere liye hi jiya main', 1),
  (1024, 178, 'Khud ko jo yun de diya hai', 1),
  (1025, 182, 'Teri wafa ne mujhko sambhala', 1),
  (1026, 188, 'Saare ghamon ko dil se nikala', 1),
  (1027, 193, 'Tere saath mera hai naseeb juda', 1),
  (1028, 198, 'Tujhe paake adhoora naa raha hmm...', 1),
  (1029, 206, 'Kyunki tum hi ho', 1),
  (1030, 209, 'Ab tum hi ho', 1),
  (1031, 211, 'Zindagi ab tum hi ho...', 1),
  (1032, 216, 'Chain bhi, mera dard bhi', 1),
  (1033, 221, 'Meri aashiqui ab tum hi ho', 1),
  (1034, 227, 'Kyunki tum hi ho', 1),
  (1035, 229, 'Ab tum hi ho', 1),
  (1036, 232, 'Zindagi ab tum hi ho...', 1),
  (1037, 237, 'Chain bhi, mera dard bhi', 1),
  (1038, 241, 'Meri aashiqui ab tum hi ho', 1);

-- Lyrics for song_id = 2 (Paisaa)
INSERT INTO song_lyrics (id, time, text, song_id) VALUES
  (2000, 0, '(Church-Church-Church)', 2),
  (2001, 2, '(Churchil dái in the beat)', 2),
  (2002, 5, 'Yeah', 2),
  (2003, 7, 'Paisaa (paisaa) tãsanga, mm-hm', 2),
  (2004, 10, 'Paisaa mãsanga, yeah', 2),
  (2005, 13, 'Paisaa (paisaa) tãsanga, mm-hm', 2),
  (2006, 16, 'Paisaa mãsanga, yeah', 2),
  (2007, 19, 'Paisaa (paisaa) tãsanga, mm-hm', 2),
  (2008, 22, 'Paisaa mãsanga, yeah', 2),
  (2009, 25, 'Paisaa (paisaa) tãsanga, mm-hm', 2),
  (2010, 28, 'Paisaa mãsanga, yeah', 2),
  (2011, 31, 'Paisaa chha dough, overload cash flow', 2),
  (2012, 34, 'Bro, bhaisakẽ bor, gani nasakine bho (ho)', 2),
  (2013, 37, 'Paisaa ko bot, paisaa jaḍeko coat mero', 2),
  (2014, 40, 'Hãshera bitáide ājabholiko nasoch, keṭo', 2),
  (2015, 43, 'Paisaa tãsanga, mm-hm', 2),
  (2016, 46, 'Paisaa (paisaa) mãsanga, yeah', 2),
  (2017, 49, 'Paisaa tãsanga, mm-hm', 2),
  (2018, 52, 'Paisaa (paisaa) mãsanga, yeah', 2),
  (2019, 55, 'Dhani ṭhūlo, choḍ kuro, money kuro bol ṭhūlo', 2),
  (2020, 58, 'Bhani ḍubo, pol khulo, ani bujho, soch kuro', 2),
  (2021, 61, 'Ambani ko Antilia mā kholidinchu penṭikhānā', 2),
  (2022, 64, 'Paisaa yeti dherai, solṭi, kamāyerai senti bhā ma', 2),
  (2023, 67, 'Āyo paisaa, gayo paisaa, dherai āyo, thorai laijā', 2),
  (2024, 70, 'Khāyo paisaa, hāgo aisā, beche āu̐cha Mona Lisa', 2),
  (2025, 73, 'Steve Jobs, better not fu*k with me dherai, ''cause', 2),
  (2026, 76, 'Kindinchu tero all company feri ma', 2),
  (2027, 79, 'Paisaa tãsanga, mm-hm', 2),
  (2028, 82, 'Paisaa (paisaa) mãsanga, yeah', 2),
  (2029, 85, 'Paisaa tãsanga, mm-hm', 2),
  (2030, 88, 'Paisaa (paisaa) mãsanga, yeah', 2),
  (2031, 91, 'Shah Rukh lāi loan bhāk, Salman ko donor ma', 2),
  (2032, 94, 'Paisaa ko golmāl, bāṇijyako owner ma', 2),
  (2033, 97, 'Sā̃ccikai bhaneko kuro sundā feri ṭhaṭṭā lācha', 2),
  (2034, 100, 'Candramā mā jaggā mero, dhanī purjā pakkā bhācha', 2),
  (2035, 103, 'Pā̃c dekhi daś, bīs, saya, pacās, mastī', 2),
  (2036, 106, 'Sakyo? La, parkhi, print huncha parsi', 2),
  (2037, 109, 'Facebook ra Insta, yo Twitter ko cintā', 2),
  (2038, 112, 'Bhan, kati lāgcha paisaa yo tīntai lāi kindā, hā?', 2),
  (2039, 115, 'Paisaa tãsanga, mm-hm', 2),
  (2040, 118, 'Paisaa (paisaa) mãsanga, yeah', 2),
  (2041, 121, 'Paisaa tãsanga, mm-hm', 2),
  (2042, 124, 'Paisaa (paisaa) mãsanga, yeah', 2),
  (2043, 127, 'Bezos nai riṇmā jaba chirchu ma scene mā', 2),
  (2044, 130, 'Bhāi Chaudhary lāi siṅgai pacāidinchu ekchinmā', 2),
  (2045, 133, 'Musk Elon le Tesla lāi katimā po beclā?', 2),
  (2046, 136, 'Bhan, testā mulā kinne paisaa bokī hiḍchu jebmā', 2),
  (2047, 139, 'Louis Vuitton, Zara, yo Gucci ra Prada ko', 2),
  (2048, 142, 'Uṭhāuchu ma bhāḍā sadhaī America jādā', 2),
  (2049, 145, 'Yo Andrew ko Tate ani Billy bhāiko gate pani', 2),
  (2050, 148, 'Joḍī mero net jati pugdaina bheṭna ni', 2),
  (2051, 151, 'Jeff pani bec, kati tespachi pani ajhai', 2),
  (2052, 154, 'Days kati lāgcha tãlāi yā̃ pugna? Decades jati', 2),
  (2053, 157, 'Hā, hā, tetī paisaa chha, bro', 2),
  (2054, 160, 'Paisaa tãsanga, mm-hm', 2),
  (2055, 163, 'Paisaa mãsanga, yeah', 2),
  (2056, 166, 'Paisaa tãsanga, mm-hm', 2),
  (2057, 169, 'Paisaa mãsanga, yeah', 2),
  (2058, 172, 'Paisaa tãsanga, mm-hm', 2),
  (2059, 175, 'Paisaa mãsanga, yeah', 2),
  (2060, 178, 'Paisaa tãsanga, mm-hm', 2),
  (2061, 181, 'Paisaa mãsanga, yeah', 2);

-- Lyrics for song_id = 3 (GOAT)
INSERT INTO song_lyrics (id, time, text, song_id) VALUES
  (3000, 13, 'Diamond de naal tolda', 3),
  (3001, 16, 'Jinna tera bhar goriye', 3),
  (3002, 18, 'Gabru taan vairi nu vi mitha bolda', 3),
  (3003, 20, 'Ni tu taan phir jatt da pyar goriye', 3),
  (3004, 23, 'Dekh bollywood vich jinne Khan ne', 3),
  (3005, 26, 'Ohna vich behnda sardar goriye', 3),
  (3006, 29, 'Gabru taan vairi nu vi mitha bolda', 3),
  (3007, 31, 'Ni tu taan phir jatt da pyar goriye', 3),
  (3008, 34, 'Tera rakha main rab rakha yaar da', 3),
  (3009, 37, 'Naam jihda laawan uthe saar goriye', 3),
  (3010, 40, 'Gabru taan vairi nu vi mitha bolda', 3),
  (3011, 42, 'Ni tu taan phir jatt da pyar goriye', 3),
  (3012, 46, 'Jolly gut bainde baala aali pag dekhdi', 3),
  (3013, 48, 'Vekh gaur naal gabru chon agg dikhdi', 3),
  (3014, 51, 'Mitha jatt kaude ghut na peevan jattiye', 3),
  (3015, 54, 'Matt uchchi mera man jama niwan jattiye', 3),
  (3016, 57, 'Pichhe kudiyan da kafala', 3),
  (3017, 59, 'Window taan ni deva hath maar goriye', 3),
  (3018, 61, 'Gabru taan vairi nu vi mitha bolda', 3),
  (3019, 64, 'Ni tu taan phir jatt da pyar goriye', 3),
  (3020, 67, 'Gall vich paya 40 lakh bolda', 3),
  (3021, 70, 'Dollar ch 80 ik hazar goriye', 3),
  (3022, 72, 'Gabru taan vairi nu vi mitha bolda', 3),
  (3023, 75, 'Ni tu taan phir jatt da pyar goriye', 3),
  (3024,100, 'Ho chal dass hi dinna je gall tauri ni', 3),
  (3025,103, 'Badi lambi success di story ni', 3),
  (3026,105, 'Kude ban ke taan dekh tera Kaur Singh di ni', 3),
  (3027,108, 'Dekh moam de statue ch vi taur Singh di', 3),
  (3028,111, 'Agge da pata ni jatt nu', 3),
  (3029,113, 'Changa chali janda so far goriye', 3),
  (3030,116, 'Gabru taan vairi nu vi mitha bolda', 3),
  (3031,119, 'Ni tu taan phir jatt da pyar goriye', 3),
  (3032,122, 'Ohne long race wale ghode sunn lai', 3),
  (3033,124, 'Jihna utte assi aan sawar goriye', 3),
  (3034,127, 'Gabru taan vairi nu vi mitha bolda', 3),
  (3035,129, 'Ni tu taan phir jatt da pyar goriye', 3),
  (3036,142, 'Ae yo G-Funk!', 3),
  (3037,155, 'Ho enha ho gaya tazurba ni sikheya peya', 3),
  (3038,157, 'Hale wish aa peya de utte tikkeya peya', 3),
  (3039,160, 'Ghumi game aaya fame jatt same ni', 3),
  (3040,163, 'Kar search Dosanjh’aa aala name ni', 3),
  (3041,166, 'Tera Aujla ni Aujla', 3),
  (3042,168, 'Baahleyan di range vichon bahar goriye', 3),
  (3043,171, 'Gabru taan vairi nu vi mitha bolda', 3),
  (3044,173, 'Ni tu taan phir jatt da pyar goriye', 3),
  (3045,176, 'Chan chan aakh ke bulaya kar tu', 3),
  (3046,179, 'Log bhawein kehnde ne star goriye', 3),
  (3047,182, 'Gabru taan vairi nu vi mitha bolda', 3),
  (3048,184, 'Ni tu taan phir jatt da pyar goriye', 3);
